version: 2
updates:

  - package-ecosystem: npm
    directory: '/app'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 20
    reviewers:
      - simondean
    assignees:
      - simondean
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    ignore:
      - dependency-name: bootstrap
        update-types: ["version-update:semver-major"]
      - dependency-name: nuxt
        update-types: ["version-update:semver-major"]
      - dependency-name: rehype
        update-types: ["version-update:semver-major"]
      - dependency-name: rehype-raw
        update-types: ["version-update:semver-major"]
      - dependency-name: rehype-sanitize
        update-types: ["version-update:semver-major"]
      - dependency-name: remark-gfm
        update-types: ["version-update:semver-major"]
      - dependency-name: remark-parse
        update-types: ["version-update:semver-major"]
      - dependency-name: remark-rehype
        update-types: ["version-update:semver-major"]
      - dependency-name: remark-slug
        update-types: ["version-update:semver-major"]
      - dependency-name: remark-toc
        update-types: ["version-update:semver-major"]
      - dependency-name: unified
        update-types: ["version-update:semver-major"]
      - dependency-name: vfile
        update-types: ["version-update:semver-major"]
      - dependency-name: vfile-reporter
        update-types: ["version-update:semver-major"]
      - dependency-name: webpack
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - simondean
    assignees:
      - simondean
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
