version: 2
updates:

  - package-ecosystem: npm
    directory: '/app'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - simondean
    assignees:
      - simondean
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - simondean
    assignees:
      - simondean
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
