server:
  port: ${PORT:8090}
  servlet:
    context-path: /

info:
  app:
    version: ${VERSION:0.0.0}

spring:
  application:
    name: kronicle-service
  main:
    bannerMode: "OFF"
    allow-bean-definition-overriding: true
  codec:
    # Avoid WebClient throwing DataBufferLimitException with message "Exceeded limit on max bytes to buffer : 262144"
    max-in-memory-size: 10485760
  jackson:
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      USE_BIG_DECIMAL_FOR_FLOATS: true
    default-property-inclusion: non_null
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  sleuth:
    enabled: ${ZIPKIN_ENABLED:false}
    sampler:
      probability: ${ZIPKIN_SAMPLE_RATE:0.01}
    trace-id128: true
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
  server:
    port: 8091
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, openapi

plugin-manager:
  mode: deployment
  plugin-root-dirs:
    - plugins
  disabled-plugins:
    - example

plugins:
  aws:
    enabled: false
    detailed-component-descriptions: false
    copy-resource-tags-to-components: false
    create-dependencies-for-resources: true
    load-xray-trace-data: true
    tag-keys:
      component: component
      description: description
      environment: environment
      team: team
    log-fields:
      level: level
      message: message

  bitbucket-server:
    enabled: false
    timeout: 30s

  datadog:
    enabled: false
    base-url: "https://api.datadoghq.com"
    timeout: 30s

  example:
    enabled: false

  git:
    enabled: true
    repos-dir: /data/git/repos

  github:
    enabled: false
    api-base-url: https://api.github.com
    environment-id: ci
    timeout: 30s

  gitlab:
    enabled: false
    project-page-size: 100
    environment-id: ci
    timeout: 30s
    repos-cache-ttl: 1h

  gradle:
    enabled: true
    downloader:
      timeout: 2m
    download-cache:
      dir: /data/download-cache
    url-exists-cache:
      dir: /data/url-exists-cache
    pom-cache:
      dir: /data/gradle/pom-cache

  java-import:
    enabled: true

  key-software:
    enabled: true
    default-rules-enabled: true
    default-rules:
      - name: "Gradle"
        software-name-pattern: "^gradle-wrapper$$"
      - name: "Spring Boot"
        software-name-pattern: "^org.springframework.boot:"
      - name: "Guava"
        software-name-pattern: "^com.google.guava:guava$$"
      - name: "Zipkin Brave"
        software-name-pattern: "^io.zipkin.brave:brave$$"
      - name: "Dropwizard"
        software-name-pattern: "^io.dropwizard:dropwizard-core$$"
      - name: "Jackson"
        software-name-pattern: "^com.fasterxml.jackson.core:"
      - name: "Spring Cloud"
        software-name-pattern: "^org.springframework.cloud:spring-cloud-dependencies$$"
      - name: "Lombok"
        software-name-pattern: "^org.projectlombok:lombok$$"
      - name: "Kotlin"
        software-name-pattern: "^org.jetbrains.kotlin:kotlin-bom$$"
      - name: "Micronaut"
        software-name-pattern: "^io.micronaut:micronaut-bom$$"
      - name: "AWS CDK"
        software-name-pattern: "^aws-cdk$$"
      - name: "AWS SDK"
        software-name-pattern: "^aws-sdk$$"
      - name: "Vue"
        software-name-pattern: "^vue$$"
      - name: "Nuxt"
        software-name-pattern: "^nuxt$$"
      - name: "React"
        software-name-pattern: "^react$$"
      - name: "Next.js"
        software-name-pattern: "^next$$"
      - name: "Angular"
        software-name-pattern: "^@angular/core$$"

  lines-of-code:
    enabled: true

  manual-dependency:
    enabled: true

  nodejs:
    enabled: true

  openapi:
    enabled: true
    scan-codebases: true

  readme:
    enabled: true

  repo-state:
    enabled: true

  sonarqube:
    enabled: false
    base-url: http://localhost:9000
    timeout: 30s

  todo:
    enabled: true

  zipkin:
    enabled: false
    base-url: http://localhost:9411
    timeout: 2m
    trace-limit: 1000

springdoc:
  use-management-port: true
  writer-with-default-pretty-printer: true
  swagger-ui:
    enabled: false

openapi-spec:
  clear-existing-servers: true
  servers:
    - description: Kronicle Service
      url: https://demo.kronicle.tech/api
