spring:
  sleuth:
    sampler:
      probability: ${ZIPKIN_SAMPLE_RATE:1.0}

plugins:
  git:
    repos-dir: ${TMPDIR}kronicle-service/data/git/repos

  gradle:
    download-cache:
      dir: ${TMPDIR}kronicle-service/data/download-cache
    url-exists-cache:
      dir: ${TMPDIR}kronicle-service/data/url-exists-cache
    pom-cache:
      dir: ${TMPDIR}kronicle-service/data/gradle/pom-cache
