export const diagramIcons: Readonly<Record<string, string>> = {
  'aws.apigateway-restapi':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_App-Integration/Arch_64/Arch_Amazon-API-Gateway_64.svg',
  'aws.apigateway-restapi-stage':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_App-Integration/Arch_64/Arch_Amazon-API-Gateway_64.svg',
  'aws.cloudformation-stack':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Management-Governance/64/Arch_AWS-CloudFormation_64.svg',
  'aws.dynamodb-table':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Database/64/Arch_Amazon-DynamoDB_64.svg',
  'aws.ec2-internet-gateway':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Networking-Content-Delivery/64/Arch_Amazon-Virtual-Private-Cloud_64.svg',
  'aws.ec2-route-table':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Networking-Content-Delivery/64/Arch_Amazon-Virtual-Private-Cloud_64.svg',
  'aws.ec2-security-group':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Networking-Content-Delivery/64/Arch_Amazon-Virtual-Private-Cloud_64.svg',
  'aws.ec2-subnet':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Networking-Content-Delivery/64/Arch_Amazon-Virtual-Private-Cloud_64.svg',
  'aws.ec2-vpc':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Networking-Content-Delivery/64/Arch_Amazon-Virtual-Private-Cloud_64.svg',
  'aws.ecs-cluster':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Containers/64/Arch_Amazon-Elastic-Container-Service_64.svg',
  'aws.lambda-function':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Compute/64/Arch_AWS-Lambda_64.svg',
  'aws.logs-log-group':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Management-Governance/64/Arch_Amazon-CloudWatch_64.svg',
  'aws.s3-bucket':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Storage/64/Arch_Amazon-Simple-Storage-Service_64.svg',
  'aws.secretsmanager-secret':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Security-Identity-Compliance/64/Arch_AWS-Secrets-Manager_64.svg',
  'aws.ssm-parameter':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Management-Governance/64/Arch_AWS-Systems-Manager_64.svg',
  'aws.synthetics-canary':
    '/aws-architecture-icons/Architecture-Service-Icons/Arch_Management-Governance/64/Arch_Amazon-CloudWatch_64.svg',
  'kubernetes.apiextensions-k8s-io.custom-resource-definition':
    '/kubernetes-architecture-icons/resources/labeled/crd.svg',
  'kubernetes.apps.daemon-set':
    '/kubernetes-architecture-icons/resources/labeled/ds.svg',
  'kubernetes.apps.deployment':
    '/kubernetes-architecture-icons/resources/labeled/deploy.svg',
  'kubernetes.apps.replica-set':
    '/kubernetes-architecture-icons/resources/labeled/rs.svg',
  'kubernetes.config-map':
    '/kubernetes-architecture-icons/resources/labeled/cm.svg',
  'kubernetes.endpoints':
    '/kubernetes-architecture-icons/resources/labeled/ep.svg',
  'kubernetes.namespace':
    '/kubernetes-architecture-icons/resources/labeled/ns.svg',
  'kubernetes.networking-k8s-io.network-policy':
    '/kubernetes-architecture-icons/resources/labeled/netpol.svg',
  'kubernetes.node':
    '/kubernetes-architecture-icons/infrastructure_components/unlabeled/node.svg',
  'kubernetes.pod': '/kubernetes-architecture-icons/resources/labeled/pod.svg',
  'kubernetes.rbac-authorization-k8s-io.cluster-role':
    '/kubernetes-architecture-icons/resources/labeled/c-role.svg',
  'kubernetes.rbac-authorization-k8s-io.cluster-role-binding':
    '/kubernetes-architecture-icons/resources/labeled/crb.svg',
  'kubernetes.rbac-authorization-k8s-io.role':
    '/kubernetes-architecture-icons/resources/labeled/role.svg',
  'kubernetes.rbac-authorization-k8s-io.role-binding':
    '/kubernetes-architecture-icons/resources/labeled/rb.svg',
  'kubernetes.secret':
    '/kubernetes-architecture-icons/resources/labeled/secret.svg',
  'kubernetes.service':
    '/kubernetes-architecture-icons/resources/labeled/svc.svg',
  'kubernetes.service-account':
    '/kubernetes-architecture-icons/resources/labeled/sa.svg',
  'kubernetes.storage-k8s-io.storage-class':
    '/kubernetes-architecture-icons/resources/labeled/sc.svg',
}
