name: CI Branch

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:

  ci-app-build:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      nodejs: true
      caching: true
      build_tasks: app:build -x checkFrontend -x dependencyCheckAnalyze
    secrets: inherit

  ci-app-test:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      nodejs: true
      caching: true
      build_tasks: app:checkFrontend
    secrets: inherit

  ci-app-dependency-check:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      nodejs: true
      caching: true
      build_tasks: app:dependencyCheckAnalyze
    secrets: inherit

  ci-service-build:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      nodejs: false
      caching: true
      build_tasks: build -x app:build -x test -x dependencyCheckAnalyze
    secrets: inherit

  ci-service-test:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      nodejs: false
      caching: true
      build_tasks: test -x app:test
    secrets: inherit

  ci-service-dependency-check:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      nodejs: false
      caching: true
      build_tasks: dependencyCheckAnalyze -x app:dependencyCheckAnalyze
    secrets: inherit
