name: CI Branch

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:

  ci-app-build:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      nodejs: true
      build_tasks: app:build -x checkFrontend
    secrets: inherit

  ci-app-test:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      nodejs: true
      build_tasks: app:checkFrontend
      test_reports: true
    secrets: inherit

  ci-service-build:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      build_tasks: build -x app:build -x test
    secrets: inherit

  ci-service-test:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      build_tasks: test -x app:test
      test_reports: true
    secrets: inherit

  ci-e2e-test:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      nodejs: true
      run_app: true
      run_service: true
      build_tasks: app:e2e
      test_reports: true
    secrets: inherit
