name: CI Shared

on:
  workflow_call:
    inputs:
      nodejs:
        description: Whether the job will need node.js to be installed
        required: false
        default: false
        type: boolean
      caching:
        description: Whether the job should use caching for Gradle and npm dependencies
        required: false
        default: true
        type: boolean
      run_app:
        description: Whether the job should launch the frontend app
        required: false
        default: false
        type: boolean
      run_service:
        description: Whether the job should launch the backend service
        required: false
        default: false
        type: boolean
      build_tasks:
        description: The space separated names of the Gradle tasks to execute
        required: true
        type: string
      test_reports:
        description: Whether the job should archive test reports
        required: false
        default: false
        type: boolean
      cypress_outputs:
        description: Whether the job should archive cypress outputs
        required: false
        default: false
        type: boolean

jobs:

  ci-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # Based on https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Gradle packages
        if: ${{ inputs.caching }}
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Node.js
        if: ${{ inputs.nodejs }}
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Upgrade npm
        if: ${{ inputs.nodejs }}
        run: npm install -g npm@latest

      - name: Get Node.js version
        if: ${{ inputs.nodejs }}
        run: |
          echo "$(node -v)" > node-version.txt

      - name: Get npm version
        if: ${{ inputs.nodejs }}
        run: |
          echo "$(npm -v)" > npm-version.txt

      - name: Cache the NPM Cache
        if: ${{ inputs.nodejs && inputs.caching }}
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('node-version.txt', 'npm-version.txt', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6

      - name: Run the Service 🚀
        if: ${{ inputs.run_service }}
        run: |
          ./gradlew service:bootJar service:copyPlugins
          cd service
          PLUGINS_GITHUB_ENABLED=true \
            PLUGINS_GITHUB_ORGANIZATIONS_0_ACCOUNT_NAME=kronicle-tech \
            REPO_FINDERS_IGNORED_REPOS_0_URL=https://github.com/kronicle-tech/kronicle-metadata-repo-template.git \
            REPO_FINDERS_IGNORED_REPOS_1_URL=https://github.com/kronicle-tech/kronicle-metadata-codebase-template.git \
            REPO_FINDERS_IGNORED_REPOS_2_URL=https://github.com/kronicle-tech/kronicle-argocd-config.git \
            java -jar build/libs/service-*.jar &
          npx wait-on -l --httpTimeout 10000 -t 60000 http://localhost:8090/populated

      - name: Run the App 🚀
        if: ${{ inputs.run_app }}
        run: |
          ./gradlew app:assembleFrontend
          cd app
          npx nuxt start &
          npx wait-on -l --httpTimeout 10000 -t 60000 http://localhost:3000

      - name: Build
        run: |
          ./gradlew ${{ inputs.build_tasks }}

      - name: Archive JUnit test reports 🗄️
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: junit-test-reports
          path: '**/build/reports/tests/test/**'
          # See https://github.com/actions/runner/issues/409#issuecomment-727565588 for explanation of syntax
          if-no-files-found: ${{ inputs.test_reports && 'error' || 'ignore' }}

      - name: Archive Cypress outputs 🗄️
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-artifacts
          path: |
            app/cypress/screenshots/**
            app/cypress/videos/**
          if-no-files-found: ${{ inputs.cypress_outputs && 'error' || 'ignore' }}

      - name: Clean up Gradle Cache
        if: ${{ inputs.caching }}
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
