name: CI Shared

on:
  workflow_call:
    inputs:
      nodejs:
        description: Whether the job will need node.js to be installed
        required: true
        type: boolean
      caching:
        description: Whether the job should use caching for Gradle and npm dependencies
        required: true
        type: boolean
      build_tasks:
        description: The space separated names of the Gradle tasks to execute
        required: true
        type: string
      dependency_check_reports:
        description: Whether the job should archive dependency check reports
        required: true
        type: boolean
      test_reports:
        description: Whether the job should archive test reports
        required: true
        type: boolean

jobs:

  ci-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # Based on https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Gradle packages
        if: ${{ inputs.caching }}
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Node.js
        if: ${{ inputs.nodejs }}
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Upgrade npm
        if: ${{ inputs.nodejs }}
        run: npm install -g npm@latest

      - name: Get Node.js version
        if: ${{ inputs.nodejs }}
        run: |
          echo "$(node -v)" > node-version.txt

      - name: Get npm version
        if: ${{ inputs.nodejs }}
        run: |
          echo "$(npm -v)" > npm-version.txt

      - name: Cache the NPM Cache
        if: ${{ inputs.nodejs && inputs.caching }}
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('node-version.txt', 'npm-version.txt', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build
        run: |
          ./gradlew ${{ inputs.build_tasks }}

      - name: Archive Dependency Check report 🗄️
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dependency-check-report
          path: '**/build/reports/dependency-check-report.html'
          # See https://github.com/actions/runner/issues/409#issuecomment-727565588 for explanation of syntax
          if-no-files-found: ${{ inputs.dependency_check_reports && 'error' || 'ignore' }}

      - name: Archive JUnit test reports 🗄️
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: junit-test-reports
          path: '**/build/reports/tests/test/**'
          # See https://github.com/actions/runner/issues/409#issuecomment-727565588 for explanation of syntax
          if-no-files-found: ${{ inputs.test_reports && 'error' || 'ignore' }}

      - name: Clean up Gradle Cache
        if: ${{ inputs.caching }}
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
