name: CI Shared

on:
  workflow_call:
    inputs:
      uses_nodejs:
        description: Whether the job will need node.js to be installed
        required: true
        type: boolean
      build_tasks:
        description: The space separated names of the Gradle tasks to execute
        required: true
        type: string

jobs:

  ci-build:
    runs-on: ubuntu-latest
    env:
      BUILD_TASKS: ${{ inputs.build_tasks }}

    steps:
      - uses: actions/checkout@v2
        # Based on https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Node.js
        if: ${{ inputs.uses_nodejs == 'true' }}
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Upgrade npm
        if: ${{ inputs.uses_nodejs == 'true' }}
        run: npm install -g npm@latest

      - name: Get Node.js version
        if: ${{ inputs.uses_nodejs == 'true' }}
        run: |
          echo "$(node -v)" > node-version.txt

      - name: Get npm version
        if: ${{ inputs.uses_nodejs == 'true' }}
        run: |
          echo "$(npm -v)" > npm-version.txt

      - name: Cache the NPM Cache
        if: ${{ inputs.uses_nodejs == 'true' }}
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('node-version.txt', 'npm-version.txt', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build
        run: |
          ./gradlew $BUILD_TASKS

      - name: Archive Dependency Check report 🗄️
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: dependency-check-report
          path: '**/build/reports/dependency-check-report.html'

      - name: Archive JUnit test reports 🗄️
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: junit-test-reports
          path: '**/build/reports/tests/test/**'

      - name: Clean up Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
