name: CI

on: [push]

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        # Based on https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Cache Gradle packages
        uses: actions/cache@v2
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Get Node.js version
        run: |
          echo "$(node -v)" > node-version.txt

      - name: Get npm version
        run: |
          echo "$(npm -v)" > npm-version.txt

      - name: Cache the NPM Cache
        uses: actions/cache@v2
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('node-version.txt', 'npm-version.txt', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information for SonarQube, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          extra_tasks=()
          if [[ -v SONAR_TOKEN ]]; then extra_tasks+=('sonarqube'); fi
          ./gradlew service:downloadGradleLibs app:docker service:test app:assembleFrontend "${extra_tasks[@]}" build

      - name: Archive Dependency Check report 🗄️
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: dependency-check-report
          path: '**/build/reports/dependency-check-report.html'

      - name: Archive JUnit test reports 🗄️
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: junit-test-reports
          path: '**/build/reports/tests/test/**'

      - name: Tag build
        if: ${{ github.ref == 'refs/heads/main' }}
        # Based on https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions
        run: ./gradlew release -Prelease.customUsername=${{ github.actor }} -Prelease.customPassword=${{ github.token }}

      - name: Publish JARs to Maven Central
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./gradlew --no-parallel publish
        working-directory: repo
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      - name: Log in to GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images to GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./gradlew -PdockerPushImage=true -PdockerRegistry=ghcr.io/kronicle-tech -PdockerTagSuffix=-pre-release dockerPush
        working-directory: repo

      - name: Clean up Gradle Cache
        if: ${{ github.ref != 'refs/heads/main' }}
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
